# syntax=docker/dockerfile:1

FROM node:18-alpine
WORKDIR /app
COPY . .
RUN rm -rf node_modules && rm package-lock.json && yarn cache clean
RUN npm update && npm upgrade
RUN npm install
CMD ["npm", "start"]
EXPOSE 3000